name: dartcoin_example
description: A simple Dart library for bitcoin wallets.
version: 0.1.0
publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: '>=3.11.3 <4.0.0'

dependencies:
  args: ^2.7.0
  dartcoin:
    path: ../
