include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**, example_flutter/**]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true

formatter:
  page_width: 80
