# This is a basic workflow to help you get started with Actions

name: flutter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: wget https://bitcoincore.org/bin/bitcoin-core-29.0/bitcoin-29.0-x86_64-linux-gnu.tar.gz
      - run: tar -C /tmp -xzf bitcoin-29.0-x86_64-linux-gnu.tar.gz
      - run: echo "BITCOIN_CORE_BIN=/tmp/bitcoin-29.0/bin/bitcoind" >> $GITHUB_ENV
      - run: $BITCOIN_CORE_BIN --version
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed lib/
      - run: dart analyze
      - run: dart test test/*
